# permissions for end users to view opsconfiginfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: opsconfiginfo-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: altershieldoperator
    app.kubernetes.io/part-of: altershieldoperator
    app.kubernetes.io/managed-by: kustomize
  name: opsconfiginfo-viewer-role
rules:
- apiGroups:
  - app.ops.cloud.alipay.com
  resources:
  - opsconfiginfoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.ops.cloud.alipay.com
  resources:
  - opsconfiginfoes/status
  verbs:
  - get
