//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchPodInfo) DeepCopyInto(out *BatchPodInfo) {
	*out = *in
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = make([]PodInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchPodInfo.
func (in *BatchPodInfo) DeepCopy() *BatchPodInfo {
	if in == nil {
		return nil
	}
	out := new(BatchPodInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeDefense) DeepCopyInto(out *ChangeDefense) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeDefense.
func (in *ChangeDefense) DeepCopy() *ChangeDefense {
	if in == nil {
		return nil
	}
	out := new(ChangeDefense)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChangeDefense) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeDefenseExecution) DeepCopyInto(out *ChangeDefenseExecution) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeDefenseExecution.
func (in *ChangeDefenseExecution) DeepCopy() *ChangeDefenseExecution {
	if in == nil {
		return nil
	}
	out := new(ChangeDefenseExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChangeDefenseExecution) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeDefenseExecutionList) DeepCopyInto(out *ChangeDefenseExecutionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChangeDefenseExecution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeDefenseExecutionList.
func (in *ChangeDefenseExecutionList) DeepCopy() *ChangeDefenseExecutionList {
	if in == nil {
		return nil
	}
	out := new(ChangeDefenseExecutionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChangeDefenseExecutionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeDefenseExecutionSpec) DeepCopyInto(out *ChangeDefenseExecutionSpec) {
	*out = *in
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(TargetRef)
		(*in).DeepCopyInto(*out)
	}
	if in.DefenseStrategy != nil {
		in, out := &in.DefenseStrategy, &out.DefenseStrategy
		*out = new(DefenseStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.RiskPolicy != nil {
		in, out := &in.RiskPolicy, &out.RiskPolicy
		*out = new(RiskPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeDefenseExecutionSpec.
func (in *ChangeDefenseExecutionSpec) DeepCopy() *ChangeDefenseExecutionSpec {
	if in == nil {
		return nil
	}
	out := new(ChangeDefenseExecutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeDefenseExecutionStatus) DeepCopyInto(out *ChangeDefenseExecutionStatus) {
	*out = *in
	in.DefenseStatus.DeepCopyInto(&out.DefenseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeDefenseExecutionStatus.
func (in *ChangeDefenseExecutionStatus) DeepCopy() *ChangeDefenseExecutionStatus {
	if in == nil {
		return nil
	}
	out := new(ChangeDefenseExecutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeDefenseList) DeepCopyInto(out *ChangeDefenseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChangeDefense, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeDefenseList.
func (in *ChangeDefenseList) DeepCopy() *ChangeDefenseList {
	if in == nil {
		return nil
	}
	out := new(ChangeDefenseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChangeDefenseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeDefenseSpec) DeepCopyInto(out *ChangeDefenseSpec) {
	*out = *in
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(TargetRef)
		(*in).DeepCopyInto(*out)
	}
	if in.DefenseStrategy != nil {
		in, out := &in.DefenseStrategy, &out.DefenseStrategy
		*out = new(DefenseStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.RiskPolicy != nil {
		in, out := &in.RiskPolicy, &out.RiskPolicy
		*out = new(RiskPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeDefenseSpec.
func (in *ChangeDefenseSpec) DeepCopy() *ChangeDefenseSpec {
	if in == nil {
		return nil
	}
	out := new(ChangeDefenseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeDefenseStatus) DeepCopyInto(out *ChangeDefenseStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeDefenseStatus.
func (in *ChangeDefenseStatus) DeepCopy() *ChangeDefenseStatus {
	if in == nil {
		return nil
	}
	out := new(ChangeDefenseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefenseStatus) DeepCopyInto(out *DefenseStatus) {
	*out = *in
	in.TargetStatus.DeepCopyInto(&out.TargetStatus)
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefenseStatus.
func (in *DefenseStatus) DeepCopy() *DefenseStatus {
	if in == nil {
		return nil
	}
	out := new(DefenseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefenseStrategy) DeepCopyInto(out *DefenseStrategy) {
	*out = *in
	in.Workload.DeepCopyInto(&out.Workload)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefenseStrategy.
func (in *DefenseStrategy) DeepCopy() *DefenseStrategy {
	if in == nil {
		return nil
	}
	out := new(DefenseStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefenseTargetStatus) DeepCopyInto(out *DefenseTargetStatus) {
	*out = *in
	if in.PodBatches != nil {
		in, out := &in.PodBatches, &out.PodBatches
		*out = make([]BatchPodInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefenseTargetStatus.
func (in *DefenseTargetStatus) DeepCopy() *DefenseTargetStatus {
	if in == nil {
		return nil
	}
	out := new(DefenseTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectRef) DeepCopyInto(out *ObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectRef.
func (in *ObjectRef) DeepCopy() *ObjectRef {
	if in == nil {
		return nil
	}
	out := new(ObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodInfo) DeepCopyInto(out *PodInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodInfo.
func (in *PodInfo) DeepCopy() *PodInfo {
	if in == nil {
		return nil
	}
	out := new(PodInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RiskPolicy) DeepCopyInto(out *RiskPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RiskPolicy.
func (in *RiskPolicy) DeepCopy() *RiskPolicy {
	if in == nil {
		return nil
	}
	out := new(RiskPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
	if in.ObjectRef != nil {
		in, out := &in.ObjectRef, &out.ObjectRef
		*out = new(ObjectRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRef.
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadDefenseStep) DeepCopyInto(out *WorkloadDefenseStep) {
	*out = *in
	out.Partition = in.Partition
	if in.CheckAfterComplete != nil {
		in, out := &in.CheckAfterComplete, &out.CheckAfterComplete
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadDefenseStep.
func (in *WorkloadDefenseStep) DeepCopy() *WorkloadDefenseStep {
	if in == nil {
		return nil
	}
	out := new(WorkloadDefenseStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadDefenseStrategy) DeepCopyInto(out *WorkloadDefenseStrategy) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]WorkloadDefenseStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadDefenseStrategy.
func (in *WorkloadDefenseStrategy) DeepCopy() *WorkloadDefenseStrategy {
	if in == nil {
		return nil
	}
	out := new(WorkloadDefenseStrategy)
	in.DeepCopyInto(out)
	return out
}
